param(
    [string]$ProjectPath = '',
    [string]$VaultPath = '',
    [ValidateRange(1,8)][int]$Rounds = 2,
    [ValidateSet('cuda','cpu')][string]$Device = 'cuda',
    [switch]$Compare
)
$ErrorActionPreference = 'Stop'
$desktopPath = [Environment]::GetFolderPath('Desktop')
if (!$ProjectPath) { $ProjectPath = Join-Path $env:USERPROFILE 'parameter-golf' }
if (!$VaultPath) { $VaultPath = Join-Path $desktopPath 'LainBrainTrainingTest' }
if (!(Test-Path -LiteralPath (Join-Path $VaultPath '.obsidian'))) { throw '找不到测试仓库，请用 -VaultPath 指定它。' }
if (!(Test-Path -LiteralPath (Join-Path $ProjectPath 'train_gpt.py'))) { throw '找不到 train_gpt.py，请用 -ProjectPath 指定项目。' }

# Payload generated by tools/build_auto_launcher.py from reviewed repository files.
$payloadBase64 = @'
@@PAYLOAD_BASE64@@
'@
$expectedPayloadHash = '@@PAYLOAD_SHA256@@'
$payloadBytes = [Convert]::FromBase64String($payloadBase64)
$hasher = [Security.Cryptography.SHA256]::Create()
try { $payloadHash = ([BitConverter]::ToString($hasher.ComputeHash($payloadBytes))).Replace('-','').ToLowerInvariant() }
finally { $hasher.Dispose() }
if ($payloadHash -ne $expectedPayloadHash) { throw '启动器内容校验失败，请重新下载原文件。' }

$toolPath = Join-Path $desktopPath 'lain-training-auto'
$pluginPath = Join-Path $VaultPath '.obsidian\plugins\lain-brain'
$stagingPath = Join-Path ([IO.Path]::GetTempPath()) ('lain-training-' + [Guid]::NewGuid().ToString('N'))
$backupPath = Join-Path $toolPath ('backups\' + [DateTime]::Now.ToString('yyyyMMdd-HHmmss-fff'))
$pluginChanged = $false

function Copy-VerifiedFile([string]$Source, [string]$Destination, [string]$BackupName) {
    $expected = (Get-FileHash -LiteralPath $Source -Algorithm SHA256).Hash
    if (Test-Path -LiteralPath $Destination) {
        if ((Get-FileHash -LiteralPath $Destination -Algorithm SHA256).Hash -eq $expected) { return $false }
        New-Item -ItemType Directory -Path $backupPath -Force | Out-Null
        Copy-Item -LiteralPath $Destination -Destination (Join-Path $backupPath $BackupName) -ErrorAction Stop
    }
    Copy-Item -LiteralPath $Source -Destination $Destination -ErrorAction Stop
    if ((Get-FileHash -LiteralPath $Destination -Algorithm SHA256).Hash -ne $expected) { throw "文件写入校验失败：$Destination" }
    return $true
}

try {
    New-Item -ItemType Directory -Path $stagingPath -Force | Out-Null
    $archivePath = Join-Path $stagingPath 'payload.zip'
    [IO.File]::WriteAllBytes($archivePath, $payloadBytes)
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $unpackedPath = Join-Path $stagingPath 'files'
    [IO.Compression.ZipFile]::ExtractToDirectory($archivePath, $unpackedPath)
    $payloadManifest = Get-Content -LiteralPath (Join-Path $unpackedPath 'payload-manifest.json') -Raw | ConvertFrom-Json
    foreach ($entry in $payloadManifest.files) {
        $sourceFile = Join-Path $unpackedPath $entry.path
        if ((Get-FileHash -LiteralPath $sourceFile -Algorithm SHA256).Hash.ToLowerInvariant() -ne $entry.sha256) { throw '安装文件校验失败。' }
    }
    New-Item -ItemType Directory -Path $toolPath -Force | Out-Null
    New-Item -ItemType Directory -Path $pluginPath -Force | Out-Null
    foreach ($fileName in @('auto_train.py','compare_train.py','object_train.py','laptop_train.py','model-source.sha256','README.md','LICENSE')) {
        $null = Copy-VerifiedFile (Join-Path $unpackedPath ('tools\' + $fileName)) (Join-Path $toolPath $fileName) ('tools-' + $fileName)
    }
    foreach ($fileName in @('main.js','manifest.json')) {
        $changed = Copy-VerifiedFile (Join-Path $unpackedPath ('plugin\' + $fileName)) (Join-Path $pluginPath $fileName) ('plugin-' + $fileName)
        if ($changed) { $pluginChanged = $true }
    }
} finally {
    if (Test-Path -LiteralPath $stagingPath) { Remove-Item -LiteralPath $stagingPath -Recurse -Force }
}

function Convert-ToWslPath([string]$WindowsPath) {
    $absolutePath = [IO.Path]::GetFullPath($WindowsPath)
    if ($absolutePath -notmatch '^[A-Za-z]:\\') { throw '当前启动器需要本机盘符路径。' }
    return '/mnt/' + $absolutePath.Substring(0,1).ToLowerInvariant() + '/' + $absolutePath.Substring(3).Replace('\','/')
}

if ($pluginChanged) {
    Write-Host '插件已安装或更新。请在 Obsidian 中关闭再启用 Lain Brain 一次；脚本会等待连接。' -ForegroundColor Yellow
} else {
    Write-Host '安装文件已就绪。请保持 Obsidian 的测试仓库打开。' -ForegroundColor Cyan
}
if ($Compare) {
    Write-Host '对照实验：三个种子，每个种子两组；同一冻结权重，每组 600 步（默认）。保持测试仓库打开。Ctrl+C 可以停止。'
    $runnerFileName = 'compare_train.py'
} else {
    Write-Host "自动训练 $Rounds 轮：小模型审阅、Brain 验证、保存与下一轮训练。Ctrl+C 可以停止。"
    $runnerFileName = 'auto_train.py'
}
$runnerWslPath = Convert-ToWslPath (Join-Path $toolPath $runnerFileName)
$projectWslPath = Convert-ToWslPath $ProjectPath
$vaultWslPath = Convert-ToWslPath $VaultPath
Get-Command wsl -ErrorAction Stop | Out-Null
# Windows PowerShell 5 can treat native stderr informational output as errors.
# Keep the observed WSL proxy notice visible and judge success by the exit code.
# https://devblogs.microsoft.com/powershell/powershell-7-1-preview-6/
$previousNativePreference = $ErrorActionPreference
try {
    $ErrorActionPreference = 'Continue'
    & wsl -- /root/lain-training-venv/bin/python -u $runnerWslPath --project $projectWslPath --vault $vaultWslPath --device $Device --rounds $Rounds
    $trainerExitCode = $LASTEXITCODE
} finally { $ErrorActionPreference = $previousNativePreference }
if ($trainerExitCode -ne 0) { throw "训练器已停止，退出码：$trainerExitCode。请保留上面的报错和已保存的文件。" }
